# Generated by Django 4.2.6 on 2024-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CultGreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/plant_images/'),
        ),
    ]
